version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb-container
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - mariadb-volume:/var/lib/mysql
    

  nginx:
    build: ./requirements/nginx
    container_name: nginx-container
    ports:
      - 443:443
    env_file:
      - ./.env
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress-container
    ports:
      - 9000:9000
    env_file:
      - ./.env
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/html
    


volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: volume
      device: /home/mabdelba/data/db
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      type: volume
      device: /home/mabdelba/data/wordpress
      o: bind